<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "form4_socialmedialinks"
 *
 * Auto generated by Extension Builder 2016-02-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'form4 Social Media Links',
	'description' => 'Social and share links as TYPO3 backend records (URL or small HTML). Output via content element or TypoScript; optional icons and placeholders (e.g. current page URL or title).',
	'category' => 'fe',
	'author' => 'form4 GmbH',
	'author_email' => 'typo3@form4.de',
	'author_company' => 'form4 GmbH',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '13.4.1',
	'constraints' => array(
		'depends' => array(
            'typo3' => '13.4.0-13.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);