<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "form4_socialmedialinks"
 *
 * Auto generated by Extension Builder 2016-02-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'form4 Social Media Links',
	'description' => 'Adds the ability to add any social link to your website. With this extension you can offer your vistors e.g. links to bookmark the current page (delicious, mister wong, ...), links to share on a network (facebook, twitter, ...) or anything else.',
	'category' => 'fe',
	'author' => 'form4 GmbH',
	'author_email' => 'typo3@form4.de',
	'author_company' => 'form4 GmbH',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '13.4.0',
	'constraints' => array(
		'depends' => array(
            'typo3' => '13.4.0-13.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);